import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { prisma } from "../lib/prisma";
import { computeStats, SQM_PER_SQFT } from "../lib/space-area-stats";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, "..", "lib", "space-area-stats.generated.ts");

type TypeBucket = {
  spaceTypeId: number;
  name: string;
  valuesSqft: number[];
};

// Data-quality filters applied to the source rows before they enter the
// distribution. TDSB's published sqft/sqm pairs disagree for ~7.5% of spaces,
// usually because the sqm column was filled with the linear-meter conversion
// (sqft × 0.3048) instead of the area conversion. A handful of sqft values
// are also nonsensically large (stadium-sized) and look like data-entry typos.
const DISAGREEMENT_THRESHOLD = 0.20; // drop if sqft and sqm-implied-sqft differ by >20%
const SQFT_CAP = 25000;              // drop sqft values larger than a generous school space

function disagreementPct(sqft: number, sqm: number): number {
  const impliedSqft = sqm / SQM_PER_SQFT;
  return Math.abs(sqft - impliedSqft) / Math.max(sqft, impliedSqft);
}

async function main() {
  const spaces = await prisma.space.findMany({
    where: {
      spaceTypeId: { not: null },
      OR: [{ areaSqft: { not: null } }, { areaSqm: { not: null } }],
    },
    select: {
      id: true,
      name: true,
      spaceTypeId: true,
      areaSqft: true,
      areaSqm: true,
      spaceType: { select: { id: true, name: true } },
    },
  });

  const buckets = new Map<number, TypeBucket>();
  const dropped: Array<{ id: number; name: string; reason: string; sqft: number | null; sqm: number | null }> = [];

  for (const space of spaces) {
    const type = space.spaceType;
    if (!type) continue;

    // Filter: catastrophic sqft outliers
    if (space.areaSqft != null && space.areaSqft > SQFT_CAP) {
      dropped.push({ id: space.id, name: space.name, reason: `sqft > ${SQFT_CAP}`, sqft: space.areaSqft, sqm: space.areaSqm });
      continue;
    }

    // Filter: paired values that disagree by more than DISAGREEMENT_THRESHOLD
    if (space.areaSqft != null && space.areaSqm != null) {
      const disagreement = disagreementPct(space.areaSqft, space.areaSqm);
      if (disagreement > DISAGREEMENT_THRESHOLD) {
        dropped.push({ id: space.id, name: space.name, reason: `sqft/sqm disagree by ${(disagreement * 100).toFixed(0)}%`, sqft: space.areaSqft, sqm: space.areaSqm });
        continue;
      }
    }

    // Prefer the integer sqft value as canonical; fall back to converting sqm
    // when TDSB only published one half of the pair.
    let canonicalSqft: number | null = null;
    if (space.areaSqft != null) canonicalSqft = space.areaSqft;
    else if (space.areaSqm != null) canonicalSqft = space.areaSqm / SQM_PER_SQFT;

    // Apply the sqft cap to the converted value too, so a garbage sqm-only
    // entry can't sneak through (the dual-reported variant would have been
    // caught by the SQFT_CAP check above).
    if (canonicalSqft != null && canonicalSqft > SQFT_CAP) {
      dropped.push({ id: space.id, name: space.name, reason: `converted sqft > ${SQFT_CAP}`, sqft: space.areaSqft, sqm: space.areaSqm });
      continue;
    }

    if (canonicalSqft == null) continue;

    let bucket = buckets.get(type.id);
    if (!bucket) {
      bucket = { spaceTypeId: type.id, name: type.name, valuesSqft: [] };
      buckets.set(type.id, bucket);
    }
    bucket.valuesSqft.push(canonicalSqft);
  }

  const ordered = [...buckets.values()].sort((a, b) => a.spaceTypeId - b.spaceTypeId);
  const records = ordered.map((bucket) => {
    const stats = computeStats(bucket.valuesSqft);
    return {
      spaceTypeId: bucket.spaceTypeId,
      name: bucket.name,
      distribution: stats ? { ...stats, values: [...bucket.valuesSqft].sort((a, b) => a - b) } : null,
    };
  }).filter((r) => r.distribution);

  const generatedAt = new Date().toISOString();
  const total = records.reduce((sum, r) => sum + (r.distribution?.count ?? 0), 0);

  const header = `// AUTO-GENERATED by scripts/compute-space-area-stats.ts. Do not edit by hand.\n// Re-run with: npm run stats:area  (after npm run sync:inventory).\n// Generated at ${generatedAt} from ${total} samples across ${records.length} space types.\n// Values are stored in canonical sqft. sqm is derived at render time.\n\n`;

  const body = `import type { SpaceAreaTypeStats } from "./space-area-stats";\n\nexport const SPACE_AREA_STATS_GENERATED_AT = ${JSON.stringify(generatedAt)} as const;\n\nexport const SPACE_AREA_STATS: SpaceAreaTypeStats[] = ${JSON.stringify(records, null, 2)};\n\nexport const SPACE_AREA_STATS_BY_TYPE: Record<number, SpaceAreaTypeStats> = Object.fromEntries(\n  SPACE_AREA_STATS.map((row) => [row.spaceTypeId, row]),\n);\n`;

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, header + body, "utf8");

  console.log(`wrote ${records.length} space-type entries to ${OUTPUT_PATH}`);
  for (const r of records) {
    const d = r.distribution!;
    console.log(`  [${r.spaceTypeId}] ${r.name}: n=${d.count}, mean=${Math.round(d.mean)}, median=${Math.round(d.median)} sqft`);
  }
  if (dropped.length > 0) {
    console.log(`\ndropped ${dropped.length} space rows as unreliable:`);
    for (const row of dropped) {
      console.log(`  id=${row.id} "${row.name}" — ${row.reason} (sqft=${row.sqft}, sqm=${row.sqm})`);
    }
  }
}

try {
  await main();
} finally {
  await prisma.$disconnect();
}
